(* QCheck lattice-law and structural-invariant tests for the subpolyhedra domain.

   States are generated by applying random sequences of domain operations
   (assignments, guards, havocs, joins, meets, widenings) over a small fixed
   environment, so only reachable states are tested — arbitrary matrices would
   violate representation invariants the operations themselves maintain. *)

open OUnit2
open QCheck
open Goblint_lib

module D = SubPolyhedraDomain.D

let prog_vars = List.map GobApron.Var.of_string ["x"; "y"; "z"]
let base = D.add_vars (D.top ()) prog_vars

(* constant and one small coefficient per program variable *)
type linexp = int * int list

type op =
  | Assign of int * linexp
  | Guard of int * linexp (* constraint type index, expression ⋈ 0 *)
  | Forget of int
  | JoinWith of op list
  | MeetWith of op list
  | WidenWith of op list

let texpr_of ((k, cs): linexp) : Apron.Texpr1.expr =
  let open Apron.Texpr1 in
  List.fold_left2 (fun acc c v ->
      if c = 0 then acc
      else Binop (Add, acc, Binop (Mul, Cst (Apron.Coeff.s_of_int c), Var v, Int, Near), Int, Near))
    (Cst (Apron.Coeff.s_of_int k)) cs prog_vars

let typ_of = function
  | 0 -> Apron.Tcons1.EQ
  | 1 -> Apron.Tcons1.SUPEQ
  | 2 -> Apron.Tcons1.SUP
  | _ -> Apron.Tcons1.DISEQ

let rec apply (t: D.t) (op: op) : D.t =
  match op with
  | Assign (i, e) -> D.assign_texpr t (List.nth prog_vars i) (texpr_of e)
  | Guard (ty, e) ->
    if D.is_bot_env t then t
    else
      let texpr1 = Apron.Texpr1.of_expr (D.env t) (texpr_of e) in
      D.meet_tcons t (Apron.Tcons1.make texpr1 (typ_of ty))
  | Forget i -> D.forget_vars t [List.nth prog_vars i]
  | JoinWith ops -> D.join t (run ops)
  | MeetWith ops -> D.meet t (run ops)
  | WidenWith ops -> D.widen t (D.join t (run ops))

and run (ops: op list) : D.t = List.fold_left apply base ops

let gen_linexp : linexp Gen.t =
  Gen.(map2 (fun k cs -> (k, cs)) (int_range (-8) 8) (list_size (return 3) (int_range (-2) 2)))

let gen_op : op Gen.t =
  Gen.(fix (fun self depth ->
      let leaf = oneof [
          map2 (fun i e -> Assign (i, e)) (int_bound 2) gen_linexp;
          map2 (fun ty e -> Guard (ty, e)) (int_bound 3) gen_linexp;
          map (fun i -> Forget i) (int_bound 2);
        ]
      in
      if depth = 0 then leaf
      else
        oneof_weighted [
          6, leaf;
          1, map (fun ops -> JoinWith ops) (list_size (int_bound 4) (self (depth - 1)));
          1, map (fun ops -> MeetWith ops) (list_size (int_bound 4) (self (depth - 1)));
          1, map (fun ops -> WidenWith ops) (list_size (int_bound 4) (self (depth - 1)));
        ]
    ) 2)

let gen_state : D.t Gen.t =
  Gen.(oneof_weighted [
      1, return D.bot_env;
      1, return base;
      10, map run (list_size (int_bound 10) gen_op);
    ])

(* Lattice wrapper for DomainProperties: lattice laws are stated up to the
   order's equivalence. Structural equality distinguishes states that differ
   only in redundant slack dimensions or environment layout, so [equal] is
   mutual [leq] here. [D.bot ()] (inherited from VarManagementOps) is an empty
   non-bottom state; the actual bottom element is [bot_env]. *)
module L = struct
  include D
  let bot () = D.bot_env
  let is_bot = D.is_bot_env
  let equal a b = D.leq a b && D.leq b a
  let arbitrary () = QCheck.make ~print:D.show gen_state
end

module E = DomainProperties.Equal (L)
module Le = DomainProperties.Leq (L)
module J = DomainProperties.Join (L)
module M = DomainProperties.Meet (L)
module B = DomainProperties.Bot (L)
module T = DomainProperties.Top (L)
module C = DomainProperties.Connect (L)
module W = DomainProperties.Widen (L)
module N = DomainProperties.Narrow (L)

(* Custom properties *)

let arb = L.arbitrary ()

let test ?(count=100) name = Test.make ~count ~long_factor:10 ~name:("subpoly: " ^ name)

let no_violations op t =
  match D.check_invariants t with
  | [] -> true
  | vs -> Test.fail_reportf "%s violates invariants: %s@.state: %s" op (String.concat "; " vs) (D.show t)

(* generated states are built through operation sequences, so this checks that
   every operation preserves the structural invariants *)
let invariants_state =
  test "invariants of generated states" arb
    (fun a -> no_violations "generation" a)

let invariants_ops =
  test "invariants preserved by lattice ops" (pair arb arb)
    (fun (a, b) ->
       no_violations "join" (D.join a b)
       && no_violations "meet" (D.meet a b)
       && no_violations "widen" (D.widen a (D.join a b))
       && no_violations "narrow" (D.narrow a b))

(* solver termination: iterating x <- widen x (join x b) over any cycle of
   states must reach a structural fixpoint (solvers detect stabilization with
   structural equality) *)
let widen_chain =
  test ~count:50 "widening chains stabilize" (pair arb (list_size (Gen.int_range 1 3) arb))
    (fun (a, bs) ->
       let step x b = D.widen x (D.join x b) in
       let pass x =
         List.fold_left (fun (x, changed) b ->
             let x' = step x b in
             (x', changed || not (D.equal x x'))
           ) (x, false) bs
       in
       let rec go x n =
         if n = 0 then Test.fail_reportf "widening chain did not stabilize; state: %s" (D.show x)
         else
           let (x', changed) = pass x in
           if changed then go x' (n - 1) else true
       in
       go a 50)

let tests =
  E.tests @ Le.tests @ J.tests @ M.tests @ B.tests @ T.tests @ C.tests @ W.tests @ N.tests
  @ [invariants_state; invariants_ops; widen_chain]

let test () =
  "subPolyhedraDomain" >::: QCheck_ounit.to_ounit2_test_list tests
